# Generated by Django 3.0.6 on 2021-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Student_ID', models.IntegerField()),
                ('Username', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Approvel', models.BooleanField(default=False, verbose_name='Approved')),
                ('School', models.CharField(max_length=100)),
                ('Program', models.CharField(max_length=100)),
                ('Batch', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
