name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          args: pylint --rcfile=.pylintrc crudoper_project
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pipfile.txt
      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
