name: Pylint

on: [push, pull_request, pull_request_review, pull_request_target, pull_request_review_comment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc crudoper_project
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        find . -name '*.py' -exec pylint {} \;
