name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          args: pylint --rcfile=.pylintrc crudoper_project
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pipfile.txt
      - name: Analysing the code with pylint
        run: |
          pylint `ls -R|grep .py$|xargs`
      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
      - name: Python Pylint Github Action
        # You may pin to the exact commit or the version.
        # uses: fylein/python-pylint-github-action@cd8c363096fbae2650aef4bd02c670cb8a0c02c8
        uses: fylein/python-pylint-github-action@v4
